### ISSUE TITLE
UnityStackTracerParser error in Unity 6.3 LTS

### ISSUE THREAD

**Issue by bakhtiar-id** [PostHog/posthog-unity#106]
### Version

1.0.4

### Steps to Reproduce

Update from Unity 6.2 project to 6.3 LTS this error will persist even after deleting Library folder (refresh) and updated to latest version

### Expected Result

Library\PackageCache\com.posthog.unity@76870d1c57f1\Runtime\ErrorTracking\ExceptionPropertiesBuilder.cs(72,26): error CS0103: The name 'UnityStackTraceParser' does not exist in the current context

Library\PackageCache\com.posthog.unity@76870d1c57f1\Runtime\ErrorTracking\ExceptionPropertiesBuilder.cs(118,30): error CS0103: The name 'UnityStackTraceParser' does not exist in the current context

### Actual Result

No errors it should be able to work normally

**Comment by marandaneto** [comment]
@bakhtiar-id can you share this info:  

 - Full Unity compiler log, not just the two CS0103 lines.
 - Packages/manifest.json and Packages/packages-lock.json.
 - Whether Library/PackageCache/com.posthog.unity@76870d1c57f1/Runtime/ErrorTracking/UnityStackTraceParser.cs actually
   exists.
 - Exact Unity version string.

 If the file is missing from their PackageCache, this is likely a Unity Package Manager cache/lock/install issue. can you clean cache/reinstall and does the file exist now?

Make sure you are using the latest version of the SDK as well

**Comment by bakhtiar-id** [comment]
@marandaneto oh yes i tried with an empty project it works fine there's no issue.
What do you mean by clean cache/reinstall? do i remove the plugin and add back in or delete the Library folder?

Its unity 6000.3.18f1 when i migrated from 6000.2.10f1
I will get back to you for the rest info like the compiler log, manifest.json because we reverted back to the old version upon seeing the errors

**Comment by bakhtiar-id** [comment]
Hey I managed to fixed it, i tried reimporting all assets, clearing the Library cache and unity global cache none seem to work but after I read the error again the GUID is conflicting with another plugin

GUID [a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6] for asset 'Packages/com.posthog.unity/Runtime/ErrorTracking/UnityStackTraceParser.cs' conflicts with: 'Packages/com.xxxx.xxxx-xxxx/Docs/images' (current owner) We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.

Which I'm surprise that UUID collision is still a thing, but all good. I'm gonna close this issue.
